/**:
  controller_manager:
    ros__parameters:
      update_rate: 300  # Hz
      thread_priority: 20
      cpu_affinity: [1, 2, 3]

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      torque_controller:
        type: torque_controller/TorqueController

/**:
  torque_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - effort
      state_interfaces:
        - position
        - velocity
      compensate_gravity: true
      command_timeout: 0.1
      kinetic_friction_scalars:
        - 1.0
        - 1.0
        - 1.0
        - 0.03
        - 0.03
        - 0.03
      static_friction_scalars:
        - 0.5
        - 0.5
        - 0.5
        - 0.0
        - 0.0
        - 0.0
      static_friction_offsets:
        - 0.1
        - 0.1
        - 0.1
        - 0.0
        - 0.0
        - 0.0
      static_friction_velocity_thresholds:
        - 0.1
        - 0.1
        - 0.1
        - 0.0
        - 0.0
        - 0.0
      torque_scaling_factors:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 1.0
