joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    # step_names: [step1]  # Names of the steps
    step_names: [step1, step2]  # Names of the steps
    # Step 1: Move to all-zero pose
    step1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # Step 2: Move to initial position
    step2: [0.0076, -1.6413, 1.5930, 1.4718, 0.1012, -0.0291]
    
    duration: 5.0
    epsilon: 0.3
    action_topic: '/arm_controller/follow_joint_trajectory'
    joint_states_topic: '/joint_states'
