joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - gripper_joint_1

    step_names: [step1, step2]  # Names of the steps

    step1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    step2: [0.0, -1.57, 1.57, 1.57, 0.0, 0.0]

    duration: 5.0
    epsilon: 0.15
    action_topic: '/arm_controller/follow_joint_trajectory'
    joint_states_topic: '/joint_states'
