# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  joint6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint1:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint2:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint3:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint4:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint5:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint6:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint7:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint8:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint9:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint10:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint11:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint12:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint13:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint14:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint15:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint16:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint17:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint18:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint19:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
  finger_r_joint20:
    has_velocity_limits: true
    max_velocity: 5.0
    has_acceleration_limits: true
    max_acceleration: 5.0
