# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  rh_l1:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  rh_l2:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  rh_r1_joint:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  rh_r2:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint1:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint2:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint3:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint4:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint5:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
  joint6:
    has_velocity_limits: true
    max_velocity: 4.7999999999999998
    has_acceleration_limits: true
    max_acceleration: 18.7253757
