# Configuration for Open Manipulator Y initial positions

joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    step_names: [home, ready]  # Names of the steps

    home: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # Initial position
    ready: [0.0, -1.0, 1.0, 0.0, 0.0, 0.0]  # Ready position

    duration: 10.0
    epsilon: 0.01
    action_topic: '/arm_controller/follow_joint_trajectory'
    joint_states_topic: '/joint_states'
