/follower/controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_gripper_controller:
      type: position_controllers/GripperActionController
    right_gripper_controller:
      type: position_controllers/GripperActionController

/follower/joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_gripper_joint_1
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_gripper_joint_1
    interfaces: [position, velocity]

/follower/left_arm_controller:
  ros__parameters:
    joints: [left_joint1, left_joint2, left_joint3, left_joint4, left_joint5]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false

/follower/right_arm_controller:
  ros__parameters:
    joints: [right_joint1, right_joint2, right_joint3, right_joint4, right_joint5]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false

/follower/left_gripper_controller:
  ros__parameters:
    joint: left_gripper_joint_1

/follower/right_gripper_controller:
  ros__parameters:
    joint: right_gripper_joint_1
